package com.mcpserver.workflow;

public enum WorkflowState {
    EXTRACTING, VALIDATING, GUARDING, PREVIEWING, AWAITING_CONFIRMATION, AWAITING_INPUT, EXECUTING, CONFIRMED, REJECTED, FAILED, EXPIRED
}
