export type NodeType = "FOLDER" | "FILE";

export interface FileNode {
  id: string;
  parentId: string | null;
  name: string;
  type: NodeType;
  size: number;
  mimeType: string | null;
  owner: string;
  visibility: string;
  createdAt: string;
  updatedAt: string;
  version: number;
}

const API = "/api/files";

async function json<T>(res: Response): Promise<T> {
  if (!res.ok) {
    const body = await res.json().catch(() => ({ error: res.statusText }));
    throw new Error(body.error ?? `Request failed (${res.status})`);
  }
  return res.json() as Promise<T>;
}

export async function fetchRoot(): Promise<FileNode> {
  return json<FileNode>(await fetch(API));
}

export async function fetchChildren(id: string): Promise<FileNode[]> {
  return json<FileNode[]>(await fetch(`${API}/${id}/children`));
}

export async function fetchPath(id: string): Promise<FileNode[]> {
  return json<FileNode[]>(await fetch(`${API}/${id}/path`));
}

export async function createFolder(
  parentId: string,
  name: string,
): Promise<FileNode> {
  return json<FileNode>(
    await fetch(`${API}/${parentId}/folders`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name, owner: "you", visibility: "everyone" }),
    }),
  );
}

export async function uploadFile(
  parentId: string,
  file: File,
): Promise<FileNode> {
  const form = new FormData();
  form.append("file", file);
  return json<FileNode>(
    await fetch(`${API}/${parentId}/upload`, {
      method: "POST",
      body: form,
    }),
  );
}

export interface BulkUploadResult {
  foldersCreated: number;
  filesUploaded: number;
  filesSkipped: number;
  totalFiles: number;
}

/**
 * Upload a whole folder hierarchy. Each file carries its `webkitRelativePath`
 * (e.g. "MyFolder/sub/a.txt"); the server recreates the tree under parentId.
 */
export async function uploadFolder(
  parentId: string,
  files: File[],
): Promise<BulkUploadResult> {
  const form = new FormData();
  for (const file of files) {
    const relative =
      (file as File & { webkitRelativePath?: string }).webkitRelativePath ||
      file.name;
    form.append("files", file);
    form.append("paths", relative);
  }
  return json<BulkUploadResult>(
    await fetch(`${API}/${parentId}/upload-folder`, {
      method: "POST",
      body: form,
    }),
  );
}

/**
 * Snapshot of the server-side ingestion queue (text extraction → chunking →
 * embedding, or lexical-only indexing). Ingestion runs in the background after
 * the upload request returns; polled while active to drive the progress bar.
 */
export interface IngestionProgress {
  active: boolean;
  phase: "idle" | "starting" | "extracting" | "chunking" | "embedding" | "indexing";
  fileName: string | null;
  fileIndex: number;
  totalFiles: number;
  chunksDone: number;
  chunksTotal: number;
  updatedAt: number;
}

export async function fetchIngestionProgress(): Promise<IngestionProgress> {
  return json<IngestionProgress>(await fetch(`${API}/ingestion-progress`));
}

export async function deleteNode(id: string): Promise<void> {
  const res = await fetch(`${API}/${id}`, { method: "DELETE" });
  if (!res.ok && res.status !== 204) {
    const body = await res.json().catch(() => ({ error: res.statusText }));
    throw new Error(body.error ?? `Delete failed (${res.status})`);
  }
}

/* ── Search (RAG context path, plan.md §5.6, §5.8) ── */

export interface SearchResult {
  id: string;
  sourceName: string;
  sourcePath: string;
  sourceUrl: string;
  sourceKind: string;
  excerpt: string;
  description: string;
  content: string;
  score: number;
  aclTags: string[];
  position: number;
}

/** JSON Schema subset generated by the spec parsers (type/properties/required/enum/default). */
export interface JsonSchema {
  type: string;
  properties?: Record<string, JsonSchemaProperty>;
  required?: string[];
}

export interface JsonSchemaProperty {
  type: string;
  description?: string;
  enum?: (string | number)[];
  default?: unknown;
}

/** Summary of an imported tool as returned inside search responses. */
export interface ToolSummary {
  id: string;
  name: string;
  appSlug: string;
  displayName: string;
  description: string;
  method: string;
  enabled: boolean;
  pending: boolean;
  primaryParam: string | null;
  paramsSchema: JsonSchema;
}

export interface ToolViolation {
  param: string;
  expected: string;
  message: string;
}

export interface ToolExecution {
  status: number;
  latencyMs: number;
  contentType: string;
  body: string;
  truncated: boolean;
  request: string;
  headers?: Record<string, string>;
}

export interface ToolPreview {
  method: string;
  url: string;
  body?: string;
  headers?: Record<string, string>;
  contentType?: string;
}

/** Same four modes a connection itself supports — see DECISIONS.md. Read (GET) tools only. */
export interface AuthOverride {
  mode: "NONE" | "BASIC" | "BEARER" | "API_KEY_HEADER";
  username?: string;
  secret?: string;
  headerName?: string;
}

/**
 * Per-invocation request customization layered on top of a tool's schema-derived shape — the
 * request builder's "override anything before sending" seam. Never persisted for write tools
 * (see ApiToolExecutor.InvokeOverrides on the backend); auth override is read-tools-only.
 */
export interface RequestOverrides {
  extraHeaders?: Record<string, string>;
  extraQueryParams?: Record<string, string>;
  bodyMode?: "SCHEMA" | "NONE" | "RAW";
  rawBody?: string;
  rawContentType?: string;
  auth?: AuthOverride;
}

export interface SearchResponse {
  query: string;
  mode: "rag" | "tool" | "tool-form" | "tool-confirm" | "tool-result" | "empty" | "notReady";
  results: SearchResult[];
  total?: number;
  localCount?: number;
  webCount?: number;
  web?: boolean;
  webReady?: boolean;
  webMessage?: string;
  lexicalOnly?: boolean;
  lexicalMessage?: string;
  tool?: string;
  message?: string;
  requiresSetup?: string[];
  pluginStatus?: {
    id: string;
    name: string;
    status: PluginStatus;
    ready: boolean;
    health: string;
  }[];
  // tool modes (§5.8 # grammar):
  toolInfo?: ToolSummary;
  suggestions?: ToolSummary[];
  prefill?: Record<string, unknown>;
  missingRequired?: string[];
  violations?: ToolViolation[];
  error?: string;
  result?: ToolExecution;
  preview?: ToolPreview;
  args?: Record<string, unknown>;
  // Phase 3: confirmation token fields for write tools
  confirmationToken?: string;
  tokenExpiresAt?: string;
  workflowId?: string;
}

export async function search(query: string, topK = 20, web = false): Promise<SearchResponse> {
  return json<SearchResponse>(
    await fetch(`/api/search?q=${encodeURIComponent(query)}&topK=${topK}&web=${web}`),
  );
}

/* ── Reports and dashboards (.rql / .rqd) ── */

export type QueryDiagnosticSeverity = "ERROR" | "WARNING" | "INFO" | "HINT";

export interface SourceSpan {
  startOffset: number;
  endOffset: number;
  startLine: number;
  startCol: number;
  endLine: number;
  endCol: number;
}

export interface QueryDiagnostic {
  span: SourceSpan;
  severity: QueryDiagnosticSeverity;
  code: string;
  message: string;
}

export interface QueryCompletion {
  label: string;
  kind: string;
  detail: string;
  insertText: string;
  replaceSpan: SourceSpan;
}

export interface QuerySymbol {
  name: string;
  kind: string;
  span: SourceSpan;
  schema: string[];
}

export interface RqlAnalysis {
  diagnostics: QueryDiagnostic[];
  completions: QueryCompletion[];
  symbols: QuerySymbol[];
}

export interface DashboardParam {
  name: string;
  type: string;
  defaultValue: unknown;
}

export interface DashboardComponent {
  type: string;
  props: Record<string, string>;
  span: SourceSpan;
}

export interface DashboardAnalysis {
  diagnostics: QueryDiagnostic[];
  completions: QueryCompletion[];
  params: DashboardParam[];
  outline: DashboardComponent[];
}

export interface DashboardDataset {
  columns: string[];
  rows: Record<string, unknown>[];
  schema: Record<string, string>;
}

export interface DashboardData {
  datasets: Record<string, DashboardDataset>;
  diagnostics: QueryDiagnostic[];
  params: DashboardParam[];
  outline: DashboardComponent[];
}

export async function analyzeRql(input: {
  source: string;
  connectionId?: string;
  cursorOffset?: number;
}): Promise<RqlAnalysis> {
  return json<RqlAnalysis>(
    await fetch("/api/reports/analyze", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(input),
    }),
  );
}

export async function analyzeDashboard(input: {
  source: string;
  connectionId?: string;
  cursorOffset?: number;
}): Promise<DashboardAnalysis> {
  return json<DashboardAnalysis>(
    await fetch("/api/dashboards/analyze", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(input),
    }),
  );
}

export async function loadDashboardData(input: {
  source: string;
  connectionId?: string;
  parameters?: Record<string, unknown>;
}): Promise<DashboardData> {
  return json<DashboardData>(
    await fetch("/api/dashboards/data", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(input),
    }),
  );
}

/* ── Plugins ── */

export type PluginStatus =
  | "NOT_INSTALLED"
  | "INSTALLING"
  | "INSTALLED"
  | "ACTIVE"
  | "ERROR"
  | "DISABLED";

export interface PluginInfo {
  id: string;
  name: string;
  description: string;
  category: "REQUIRED" | "OPTIONAL";
  builtin: boolean;
  status: PluginStatus;
  enabled: boolean;
  running: boolean;
  ready: boolean;
  health: string;
}

export interface PluginJob {
  jobId: string;
  pluginId: string;
  status: "running" | "completed" | "failed";
  error?: string;
}

const PLUGINS_API = "/api/plugins";

export async function listPlugins(): Promise<PluginInfo[]> {
  return json<PluginInfo[]>(await fetch(PLUGINS_API));
}

export async function installPlugin(id: string): Promise<{ jobId: string; status: string }> {
  return json(await fetch(`${PLUGINS_API}/${id}/install`, { method: "POST" }));
}

export async function enablePlugin(id: string): Promise<PluginInfo> {
  return json<PluginInfo>(await fetch(`${PLUGINS_API}/${id}/enable`, { method: "POST" }));
}

export async function disablePlugin(id: string): Promise<PluginInfo> {
  return json<PluginInfo>(await fetch(`${PLUGINS_API}/${id}/disable`, { method: "POST" }));
}

export async function startPlugin(id: string): Promise<PluginInfo> {
  return json<PluginInfo>(await fetch(`${PLUGINS_API}/${id}/start`, { method: "POST" }));
}

export async function stopPlugin(id: string): Promise<PluginInfo> {
  return json<PluginInfo>(await fetch(`${PLUGINS_API}/${id}/stop`, { method: "POST" }));
}

export async function getPluginJob(jobId: string): Promise<PluginJob> {
  return json<PluginJob>(await fetch(`${PLUGINS_API}/jobs/${jobId}`));
}

/* ── Connections (Confluence/Jira/API-collection ingestion connectors) ── */

export type ConnectionType = "CONFLUENCE" | "JIRA" | "SHAREPOINT" | "API_COLLECTION" | "GITHUB";
export type DeploymentType = "CLOUD" | "SERVER_DC" | "UNKNOWN";
export type ConnectionStatus = "PENDING" | "CONNECTED" | "ERROR" | "DISABLED";
export type AuthMode = "BASIC" | "OAUTH2" | "NONE" | "BEARER" | "API_KEY_HEADER";

export interface ConnectionInfo {
  id: string;
  type: ConnectionType;
  name: string;
  baseUrl: string;
  deploymentType: DeploymentType;
  authMode: AuthMode;
  authUsername: string | null;
  status: ConnectionStatus;
  lastError?: string;
  webhookRegistered: boolean;
  aclScope: string[];
  specSourceUrl?: string;
  specFormat?: "POSTMAN" | "OPENAPI";
  createdAt: string;
  updatedAt: string;
  lastSyncedAt?: string;
}

export interface ConnectionJob {
  jobId: string;
  connectionId: string;
  kind: "TEST_CONNECTION" | "BACKFILL";
  status: "running" | "completed" | "failed";
  itemsProcessed?: number;
  itemsTotal?: number;
  error?: string;
}

export interface CreateConnectionInput {
  type: ConnectionType;
  name: string;
  baseUrl: string;
  username: string;
  password: string;
  aclScope?: string[];
  // API_COLLECTION only:
  specUrl?: string;
  authMode?: AuthMode;
  apiKeyHeader?: string;
}

const CONNECTIONS_API = "/api/connections";

export async function listConnections(): Promise<ConnectionInfo[]> {
  return json<ConnectionInfo[]>(await fetch(CONNECTIONS_API));
}

export async function createConnection(
  input: CreateConnectionInput,
): Promise<{ id: string; jobId: string; status: string }> {
  return json(
    await fetch(CONNECTIONS_API, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(input),
    }),
  );
}

export async function getConnection(id: string): Promise<ConnectionInfo> {
  return json<ConnectionInfo>(await fetch(`${CONNECTIONS_API}/${id}`));
}

export interface UpdateConnectionInput {
  name?: string;
  baseUrl?: string;
  username?: string;
  password?: string;
  /** Null/omitted leaves the current mode unchanged. For API_KEY_HEADER, put the header name in username. */
  authMode?: AuthMode;
  aclScope?: string[];
}

/** Updates a connection's settings/credentials and re-tests connectivity; returns the job id. */
export async function updateConnection(
  id: string,
  input: UpdateConnectionInput,
): Promise<{ jobId: string; status: string }> {
  return json(
    await fetch(`${CONNECTIONS_API}/${id}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(input),
    }),
  );
}

export async function deleteConnection(id: string): Promise<void> {
  const res = await fetch(`${CONNECTIONS_API}/${id}`, { method: "DELETE" });
  if (!res.ok && res.status !== 204) {
    const body = await res.json().catch(() => ({ error: res.statusText }));
    throw new Error(body.error ?? `Delete failed (${res.status})`);
  }
}

export async function triggerBackfill(id: string): Promise<{ jobId: string; status: string }> {
  return json(await fetch(`${CONNECTIONS_API}/${id}/backfill`, { method: "POST" }));
}

export async function enableConnection(id: string): Promise<ConnectionInfo> {
  return json<ConnectionInfo>(await fetch(`${CONNECTIONS_API}/${id}/enable`, { method: "POST" }));
}

export async function disableConnection(id: string): Promise<ConnectionInfo> {
  return json<ConnectionInfo>(await fetch(`${CONNECTIONS_API}/${id}/disable`, { method: "POST" }));
}

export async function getConnectionJob(jobId: string): Promise<ConnectionJob> {
  return json<ConnectionJob>(await fetch(`${CONNECTIONS_API}/jobs/${jobId}`));
}

/**
 * API_COLLECTION creation with an uploaded spec file (Postman collection / OpenAPI JSON or
 * YAML). Same result shape and async test job as the JSON create.
 */
export async function importSpecFile(input: {
  file: File;
  name: string;
  baseUrl?: string;
  authMode?: AuthMode;
  username?: string;
  password?: string;
  apiKeyHeader?: string;
}): Promise<{ id: string; jobId: string; status: string }> {
  const form = new FormData();
  form.append("file", input.file);
  form.append("name", input.name);
  if (input.baseUrl) form.append("baseUrl", input.baseUrl);
  if (input.authMode) form.append("authMode", input.authMode);
  if (input.username) form.append("username", input.username);
  if (input.password) form.append("password", input.password);
  if (input.apiKeyHeader) form.append("apiKeyHeader", input.apiKeyHeader);
  return json(await fetch(`${CONNECTIONS_API}/import-spec`, { method: "POST", body: form }));
}

/**
 * Best-effort, side-effect-free scan of a Postman collection / OpenAPI spec for its auth shape —
 * never a secret, just the mode plus (for Basic/API-key) a non-secret field identity, so the
 * connection-setup form can pre-fill the auth mode/username and let the user just type the secret.
 * `authMode: "NONE"` means nothing recognizable was found — fall back to manual selection.
 */
export async function detectImportAuth(input: {
  file?: File;
  specUrl?: string;
}): Promise<{ authMode: AuthMode; username: string | null }> {
  const form = new FormData();
  if (input.file) form.append("file", input.file);
  if (input.specUrl) form.append("specUrl", input.specUrl);
  return json(await fetch(`${CONNECTIONS_API}/detect-auth`, { method: "POST", body: form }));
}

/* ── Tools (imported from Postman/OpenAPI specs, §8) ── */

export interface ApiToolInfo {
  id: string;
  connectionId: string;
  appSlug: string;
  name: string;
  requestSlug: string;
  displayName: string;
  description: string;
  category: string;
  method: string;
  urlTemplate: string;
  enabled: boolean;
  pending: boolean;
  knowledgeSource: boolean;
  primaryParam: string | null;
  paramsSchema: JsonSchema;
  paramLocations: Record<string, "path" | "query" | "header" | "body">;
  bodyTemplate: string | null;
  origin: "IMPORTED" | "MANUAL";
  /** Null means "inherit the connection's stored auth" — see `updateToolAuth`. */
  authMode: AuthMode | null;
  authUsername: string | null;
}

export interface ToolInvokeResult {
  tool: string;
  status: number;
  latencyMs: number;
  contentType: string;
  body: string;
  truncated: boolean;
  request: string;
}

const TOOLS_API = "/api/tools";

export async function listTools(query?: string, connectionId?: string): Promise<ApiToolInfo[]> {
  const params = new URLSearchParams();
  if (query) params.set("query", query);
  if (connectionId) params.set("connectionId", connectionId);
  const qs = params.toString();
  return json<ApiToolInfo[]>(await fetch(qs ? `${TOOLS_API}?${qs}` : TOOLS_API));
}

export async function enableTool(id: string): Promise<ApiToolInfo> {
  return json<ApiToolInfo>(await fetch(`${TOOLS_API}/${id}/enable`, { method: "POST" }));
}

export async function disableTool(id: string): Promise<ApiToolInfo> {
  return json<ApiToolInfo>(await fetch(`${TOOLS_API}/${id}/disable`, { method: "POST" }));
}

export async function setToolKnowledgeSource(id: string, enabled: boolean): Promise<ApiToolInfo> {
  return json<ApiToolInfo>(
    await fetch(`${TOOLS_API}/${id}/knowledge-source`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ enabled }),
    }),
  );
}

/**
 * Invokes a tool. Read tools execute directly and resolve a {@link ToolInvokeResult}. Write
 * tools never execute here — the server returns a {@link WorkflowPreview} (confirmation token)
 * instead; the caller must render a confirm step and call {@link confirmTool} to actually run it.
 * Throws with the violation messages joined when the server answers 422. `overrides` layers
 * ad-hoc headers/query params/raw body/auth (read tools only) on top of the schema-derived
 * request — never persisted for write tools.
 */
export async function invokeTool(
  id: string,
  args: Record<string, unknown>,
  overrides?: RequestOverrides,
): Promise<ToolInvokeResult | WorkflowPreview> {
  const res = await fetch(`${TOOLS_API}/${id}/invoke`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ args, ...overrides }),
  });
  if (res.status === 422) {
    const body = await res.json().catch(() => ({ violations: [] }));
    const messages = (body.violations as ToolViolation[] | undefined)
      ?.map((v) => v.message)
      .join("; ");
    throw new Error(messages || "Arguments violate the tool's schema");
  }
  return json<ToolInvokeResult | WorkflowPreview>(res);
}

/** True when `invokeTool` returned a write-tool workflow preview rather than an executed result. */
export function isWorkflowPreview(
  res: ToolInvokeResult | WorkflowPreview,
): res is WorkflowPreview {
  return "confirmationToken" in res;
}

/**
 * Renders the request a tool would send — method, resolved URL, headers, body — without
 * executing it. Backs the request builder's live "resolved request" readout and code-snippet
 * generation; works for both read and write tools.
 */
export async function previewTool(
  id: string,
  args: Record<string, unknown>,
  overrides?: RequestOverrides,
): Promise<ToolPreview> {
  return json<ToolPreview>(
    await fetch(`${TOOLS_API}/${id}/preview`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ args, ...overrides }),
    }),
  );
}

/** One query or header field on a manually-built request (see `ManualToolInput`). */
export interface ManualParam {
  name: string;
  in: "query" | "header";
  required: boolean;
  defaultValue?: string;
  description?: string;
}

export interface ManualToolInput {
  connectionId: string;
  displayName: string;
  method: string;
  path: string;
  category?: string;
  description?: string;
  params?: ManualParam[];
  bodyTemplate?: string;
}

/** Creates a from-scratch request ("New request" / Save) against a connection. Never touched by re-import. */
export async function createManualTool(input: ManualToolInput): Promise<ApiToolInfo> {
  return json<ApiToolInfo>(
    await fetch(TOOLS_API, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(input),
    }),
  );
}

/** Updates a manual tool's shape. 409s if the tool is spec-imported. */
export async function updateManualTool(
  id: string,
  input: Omit<ManualToolInput, "connectionId">,
): Promise<ApiToolInfo> {
  return json<ApiToolInfo>(
    await fetch(`${TOOLS_API}/${id}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(input),
    }),
  );
}

export interface ToolAuthInput {
  /** Null/omitted clears the override back to "inherit from connection". */
  mode?: AuthMode;
  username?: string;
  /** Blank/omitted keeps the currently stored secret (only relevant when changing mode/username). */
  secret?: string;
}

/**
 * Sets or clears this tool's own auth override — works for imported tools too, not just manual
 * ones. Applies to both read and write tools (unlike the ephemeral per-invocation `auth` override
 * in `RequestOverrides`, which is GET-only and never persisted).
 */
export async function updateToolAuth(id: string, input: ToolAuthInput): Promise<ApiToolInfo> {
  return json<ApiToolInfo>(
    await fetch(`${TOOLS_API}/${id}/auth`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(input),
    }),
  );
}

/** Deletes a manual tool. 409s if the tool is spec-imported. */
export async function deleteManualTool(id: string): Promise<void> {
  const res = await fetch(`${TOOLS_API}/${id}`, { method: "DELETE" });
  if (!res.ok && res.status !== 204) {
    const body = await res.json().catch(() => ({ error: res.statusText }));
    throw new Error(body.error ?? `Delete failed (${res.status})`);
  }
}

/* ── Tool groups (custom groups of apps and/or individual endpoints) ── */

export interface ToolGroupInfo {
  id: string;
  slug: string;
  name: string;
  description?: string;
  appCount: number;
  toolCount: number;
  enabledToolCount: number;
}

export interface ToolGroupMemberInput {
  memberType: "APP" | "TOOL";
  memberId: string;
}

/** Group with resolved members, as returned by GET /api/groups/{id}. */
export interface ToolGroupDetail {
  id: string;
  slug: string;
  name: string;
  description?: string;
  apps: ConnectionInfo[];
  tools: ApiToolInfo[];
}

const GROUPS_API = "/api/groups";

export async function listGroups(): Promise<ToolGroupInfo[]> {
  return json<ToolGroupInfo[]>(await fetch(GROUPS_API));
}

export async function createGroup(name: string, description?: string): Promise<ToolGroupInfo> {
  return json<ToolGroupInfo>(
    await fetch(GROUPS_API, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name, description }),
    }),
  );
}

export async function getGroup(id: string): Promise<ToolGroupDetail> {
  return json<ToolGroupDetail>(await fetch(`${GROUPS_API}/${id}`));
}

export async function updateGroup(
  id: string,
  input: { name?: string; description?: string },
): Promise<ToolGroupInfo> {
  return json<ToolGroupInfo>(
    await fetch(`${GROUPS_API}/${id}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(input),
    }),
  );
}

export async function deleteGroup(id: string): Promise<void> {
  const res = await fetch(`${GROUPS_API}/${id}`, { method: "DELETE" });
  if (!res.ok && res.status !== 204) {
    const body = await res.json().catch(() => ({ error: res.statusText }));
    throw new Error(body.error ?? `Delete failed (${res.status})`);
  }
}

export async function setGroupMembers(
  id: string,
  members: ToolGroupMemberInput[],
): Promise<void> {
  const res = await fetch(`${GROUPS_API}/${id}/members`, {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ members }),
  });
  if (!res.ok) {
    const body = await res.json().catch(() => ({ error: res.statusText }));
    throw new Error(body.error ?? `Request failed (${res.status})`);
  }
}

export async function enableGroup(id: string): Promise<{ updated: number }> {
  return json<{ updated: number }>(await fetch(`${GROUPS_API}/${id}/enable`, { method: "POST" }));
}

export async function disableGroup(id: string): Promise<{ updated: number }> {
  return json<{ updated: number }>(await fetch(`${GROUPS_API}/${id}/disable`, { method: "POST" }));
}

/* ── Phase 3: Workflow confirmation + audit + metrics ── */

/** Preview + confirmation token returned for write-tool invocations. */
export interface WorkflowPreview {
  workflowId: string;
  toolId: string;
  toolName: string;
  state: string;
  confirmationToken: string;
  tokenExpiresAt: string;
  preview: ToolPreview;
  args: Record<string, unknown>;
}

/** Result after confirming or rejecting a workflow. */
export interface WorkflowResult {
  workflowId: string;
  toolName: string;
  state: string;
  result?: ToolExecution;
  error?: string;
}

/**
 * Confirm a write-tool execution using its single-use confirmation token.
 * Returns the execution result on success.
 */
export async function confirmTool(token: string): Promise<WorkflowResult> {
  return json<WorkflowResult>(
    await fetch(`${TOOLS_API}/confirm/${encodeURIComponent(token)}`, { method: "POST" }),
  );
}

/**
 * Reject a write-tool execution using its confirmation token.
 * No side effects occur; the rejection is audited.
 */
export async function rejectTool(token: string): Promise<WorkflowResult> {
  return json<WorkflowResult>(
    await fetch(`${TOOLS_API}/reject/${encodeURIComponent(token)}`, { method: "POST" }),
  );
}

/** A single audit log entry as returned by the API. */
export interface AuditEntry {
  id: number;
  eventType: string;
  toolId: string | null;
  toolName: string | null;
  workflowId: string | null;
  actor: string | null;
  arguments: string | null;
  resultSummary: string | null;
  error: string | null;
  createdAt: string;
}

export interface AuditResponse {
  items: AuditEntry[];
  total: number;
  page: number;
  size: number;
}

/**
 * Query the audit log with optional filters. All parameters are optional;
 * omitted filters return all events.
 */
export async function fetchAuditLog(opts?: {
  actor?: string;
  toolName?: string;
  eventType?: string;
  from?: string;
  to?: string;
  page?: number;
  size?: number;
}): Promise<AuditResponse> {
  const params = new URLSearchParams();
  if (opts?.actor) params.set("actor", opts.actor);
  if (opts?.toolName) params.set("toolName", opts.toolName);
  if (opts?.eventType) params.set("eventType", opts.eventType);
  if (opts?.from) params.set("from", opts.from);
  if (opts?.to) params.set("to", opts.to);
  if (opts?.page !== undefined) params.set("page", String(opts.page));
  if (opts?.size !== undefined) params.set("size", String(opts.size));
  const qs = params.toString();
  return json<AuditResponse>(await fetch(qs ? `/api/audit?${qs}` : "/api/audit"));
}

/** Summary metrics from the backend. */
export interface MetricsSummary {
  [key: string]: unknown;
}

export async function fetchMetricsSummary(): Promise<MetricsSummary> {
  return json<MetricsSummary>(await fetch("/api/metrics/summary"));
}
