export type NodeType = "FOLDER" | "FILE";

export interface FileNode {
  id: string;
  parentId: string | null;
  name: string;
  type: NodeType;
  size: number;
  mimeType: string | null;
  owner: string;
  visibility: string;
  createdAt: string;
  updatedAt: string;
  version: number;
}

const API = "/api/files";

async function json<T>(res: Response): Promise<T> {
  if (!res.ok) {
    const body = await res.json().catch(() => ({ error: res.statusText }));
    throw new Error(body.error ?? `Request failed (${res.status})`);
  }
  return res.json() as Promise<T>;
}

export async function fetchRoot(): Promise<FileNode> {
  return json<FileNode>(await fetch(API));
}

export async function fetchChildren(id: string): Promise<FileNode[]> {
  return json<FileNode[]>(await fetch(`${API}/${id}/children`));
}

export async function fetchPath(id: string): Promise<FileNode[]> {
  return json<FileNode[]>(await fetch(`${API}/${id}/path`));
}

export async function createFolder(
  parentId: string,
  name: string,
): Promise<FileNode> {
  return json<FileNode>(
    await fetch(`${API}/${parentId}/folders`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name, owner: "you", visibility: "everyone" }),
    }),
  );
}

export async function uploadFile(
  parentId: string,
  file: File,
): Promise<FileNode> {
  const form = new FormData();
  form.append("file", file);
  return json<FileNode>(
    await fetch(`${API}/${parentId}/upload`, {
      method: "POST",
      body: form,
    }),
  );
}

export interface BulkUploadResult {
  foldersCreated: number;
  filesUploaded: number;
  filesSkipped: number;
  totalFiles: number;
}

/**
 * Upload a whole folder hierarchy. Each file carries its `webkitRelativePath`
 * (e.g. "MyFolder/sub/a.txt"); the server recreates the tree under parentId.
 */
export async function uploadFolder(
  parentId: string,
  files: File[],
): Promise<BulkUploadResult> {
  const form = new FormData();
  for (const file of files) {
    const relative =
      (file as File & { webkitRelativePath?: string }).webkitRelativePath ||
      file.name;
    form.append("files", file);
    form.append("paths", relative);
  }
  return json<BulkUploadResult>(
    await fetch(`${API}/${parentId}/upload-folder`, {
      method: "POST",
      body: form,
    }),
  );
}

/**
 * Snapshot of the server-side ingestion queue (text extraction → chunking →
 * embedding, or lexical-only indexing). Ingestion runs in the background after
 * the upload request returns; polled while active to drive the progress bar.
 */
export interface IngestionProgress {
  active: boolean;
  phase: "idle" | "starting" | "extracting" | "chunking" | "embedding" | "indexing";
  fileName: string | null;
  fileIndex: number;
  totalFiles: number;
  chunksDone: number;
  chunksTotal: number;
  updatedAt: number;
}

export async function fetchIngestionProgress(): Promise<IngestionProgress> {
  return json<IngestionProgress>(await fetch(`${API}/ingestion-progress`));
}

export async function deleteNode(id: string): Promise<void> {
  const res = await fetch(`${API}/${id}`, { method: "DELETE" });
  if (!res.ok && res.status !== 204) {
    const body = await res.json().catch(() => ({ error: res.statusText }));
    throw new Error(body.error ?? `Delete failed (${res.status})`);
  }
}

/* ── Search (RAG context path, plan.md §5.6, §5.8) ── */

export interface SearchResult {
  id: string;
  sourceName: string;
  sourcePath: string;
  sourceUrl: string;
  sourceKind: string;
  excerpt: string;
  description: string;
  content: string;
  score: number;
  aclTags: string[];
  position: number;
}

/** JSON Schema subset generated by the spec parsers (type/properties/required/enum/default). */
export interface JsonSchema {
  type: string;
  properties?: Record<string, JsonSchemaProperty>;
  required?: string[];
}

export interface JsonSchemaProperty {
  type: string;
  description?: string;
  enum?: (string | number)[];
  default?: unknown;
}

/** Summary of an imported tool as returned inside search responses. */
export interface ToolSummary {
  id: string;
  name: string;
  appSlug: string;
  displayName: string;
  description: string;
  method: string;
  enabled: boolean;
  pending: boolean;
  primaryParam: string | null;
  paramsSchema: JsonSchema;
}

export interface ToolViolation {
  param: string;
  expected: string;
  message: string;
}

export interface ToolExecution {
  status: number;
  latencyMs: number;
  contentType: string;
  body: string;
  truncated: boolean;
  request: string;
}

export interface ToolPreview {
  method: string;
  url: string;
  body?: string;
}

export interface SearchResponse {
  query: string;
  mode: "rag" | "tool" | "tool-form" | "tool-confirm" | "tool-result" | "empty" | "notReady";
  results: SearchResult[];
  total?: number;
  localCount?: number;
  webCount?: number;
  web?: boolean;
  webReady?: boolean;
  webMessage?: string;
  lexicalOnly?: boolean;
  lexicalMessage?: string;
  tool?: string;
  message?: string;
  requiresSetup?: string[];
  pluginStatus?: {
    id: string;
    name: string;
    status: PluginStatus;
    ready: boolean;
    health: string;
  }[];
  // tool modes (§5.8 # grammar):
  toolInfo?: ToolSummary;
  suggestions?: ToolSummary[];
  prefill?: Record<string, unknown>;
  missingRequired?: string[];
  violations?: ToolViolation[];
  error?: string;
  result?: ToolExecution;
  preview?: ToolPreview;
  args?: Record<string, unknown>;
}

export async function search(query: string, topK = 20, web = false): Promise<SearchResponse> {
  return json<SearchResponse>(
    await fetch(`/api/search?q=${encodeURIComponent(query)}&topK=${topK}&web=${web}`),
  );
}

/* ── Plugins ── */

export type PluginStatus =
  | "NOT_INSTALLED"
  | "INSTALLING"
  | "INSTALLED"
  | "ACTIVE"
  | "ERROR"
  | "DISABLED";

export interface PluginInfo {
  id: string;
  name: string;
  description: string;
  category: "REQUIRED" | "OPTIONAL";
  builtin: boolean;
  status: PluginStatus;
  enabled: boolean;
  running: boolean;
  ready: boolean;
  health: string;
}

export interface PluginJob {
  jobId: string;
  pluginId: string;
  status: "running" | "completed" | "failed";
  error?: string;
}

const PLUGINS_API = "/api/plugins";

export async function listPlugins(): Promise<PluginInfo[]> {
  return json<PluginInfo[]>(await fetch(PLUGINS_API));
}

export async function installPlugin(id: string): Promise<{ jobId: string; status: string }> {
  return json(await fetch(`${PLUGINS_API}/${id}/install`, { method: "POST" }));
}

export async function enablePlugin(id: string): Promise<PluginInfo> {
  return json<PluginInfo>(await fetch(`${PLUGINS_API}/${id}/enable`, { method: "POST" }));
}

export async function disablePlugin(id: string): Promise<PluginInfo> {
  return json<PluginInfo>(await fetch(`${PLUGINS_API}/${id}/disable`, { method: "POST" }));
}

export async function startPlugin(id: string): Promise<PluginInfo> {
  return json<PluginInfo>(await fetch(`${PLUGINS_API}/${id}/start`, { method: "POST" }));
}

export async function stopPlugin(id: string): Promise<PluginInfo> {
  return json<PluginInfo>(await fetch(`${PLUGINS_API}/${id}/stop`, { method: "POST" }));
}

export async function getPluginJob(jobId: string): Promise<PluginJob> {
  return json<PluginJob>(await fetch(`${PLUGINS_API}/jobs/${jobId}`));
}

/* ── Connections (Confluence/Jira/API-collection ingestion connectors) ── */

export type ConnectionType = "CONFLUENCE" | "JIRA" | "SHAREPOINT" | "API_COLLECTION";
export type DeploymentType = "CLOUD" | "SERVER_DC" | "UNKNOWN";
export type ConnectionStatus = "PENDING" | "CONNECTED" | "ERROR" | "DISABLED";
export type AuthMode = "BASIC" | "OAUTH2" | "NONE" | "BEARER" | "API_KEY_HEADER";

export interface ConnectionInfo {
  id: string;
  type: ConnectionType;
  name: string;
  baseUrl: string;
  deploymentType: DeploymentType;
  authMode: AuthMode;
  authUsername: string | null;
  status: ConnectionStatus;
  lastError?: string;
  webhookRegistered: boolean;
  aclScope: string[];
  specSourceUrl?: string;
  specFormat?: "POSTMAN" | "OPENAPI";
  createdAt: string;
  updatedAt: string;
  lastSyncedAt?: string;
}

export interface ConnectionJob {
  jobId: string;
  connectionId: string;
  kind: "TEST_CONNECTION" | "BACKFILL";
  status: "running" | "completed" | "failed";
  itemsProcessed?: number;
  itemsTotal?: number;
  error?: string;
}

export interface CreateConnectionInput {
  type: ConnectionType;
  name: string;
  baseUrl: string;
  username: string;
  password: string;
  aclScope?: string[];
  // API_COLLECTION only:
  specUrl?: string;
  authMode?: AuthMode;
  apiKeyHeader?: string;
}

const CONNECTIONS_API = "/api/connections";

export async function listConnections(): Promise<ConnectionInfo[]> {
  return json<ConnectionInfo[]>(await fetch(CONNECTIONS_API));
}

export async function createConnection(
  input: CreateConnectionInput,
): Promise<{ id: string; jobId: string; status: string }> {
  return json(
    await fetch(CONNECTIONS_API, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(input),
    }),
  );
}

export async function getConnection(id: string): Promise<ConnectionInfo> {
  return json<ConnectionInfo>(await fetch(`${CONNECTIONS_API}/${id}`));
}

export async function deleteConnection(id: string): Promise<void> {
  const res = await fetch(`${CONNECTIONS_API}/${id}`, { method: "DELETE" });
  if (!res.ok && res.status !== 204) {
    const body = await res.json().catch(() => ({ error: res.statusText }));
    throw new Error(body.error ?? `Delete failed (${res.status})`);
  }
}

export async function triggerBackfill(id: string): Promise<{ jobId: string; status: string }> {
  return json(await fetch(`${CONNECTIONS_API}/${id}/backfill`, { method: "POST" }));
}

export async function enableConnection(id: string): Promise<ConnectionInfo> {
  return json<ConnectionInfo>(await fetch(`${CONNECTIONS_API}/${id}/enable`, { method: "POST" }));
}

export async function disableConnection(id: string): Promise<ConnectionInfo> {
  return json<ConnectionInfo>(await fetch(`${CONNECTIONS_API}/${id}/disable`, { method: "POST" }));
}

export async function getConnectionJob(jobId: string): Promise<ConnectionJob> {
  return json<ConnectionJob>(await fetch(`${CONNECTIONS_API}/jobs/${jobId}`));
}

/**
 * API_COLLECTION creation with an uploaded spec file (Postman collection / OpenAPI JSON or
 * YAML). Same result shape and async test job as the JSON create.
 */
export async function importSpecFile(input: {
  file: File;
  name: string;
  baseUrl?: string;
  authMode?: AuthMode;
  username?: string;
  password?: string;
  apiKeyHeader?: string;
}): Promise<{ id: string; jobId: string; status: string }> {
  const form = new FormData();
  form.append("file", input.file);
  form.append("name", input.name);
  if (input.baseUrl) form.append("baseUrl", input.baseUrl);
  if (input.authMode) form.append("authMode", input.authMode);
  if (input.username) form.append("username", input.username);
  if (input.password) form.append("password", input.password);
  if (input.apiKeyHeader) form.append("apiKeyHeader", input.apiKeyHeader);
  return json(await fetch(`${CONNECTIONS_API}/import-spec`, { method: "POST", body: form }));
}

/* ── Tools (imported from Postman/OpenAPI specs, §8) ── */

export interface ApiToolInfo {
  id: string;
  connectionId: string;
  appSlug: string;
  name: string;
  requestSlug: string;
  displayName: string;
  description: string;
  category: string;
  method: string;
  urlTemplate: string;
  enabled: boolean;
  pending: boolean;
  knowledgeSource: boolean;
  primaryParam: string | null;
  paramsSchema: JsonSchema;
}

export interface ToolInvokeResult {
  tool: string;
  status: number;
  latencyMs: number;
  contentType: string;
  body: string;
  truncated: boolean;
  request: string;
}

const TOOLS_API = "/api/tools";

export async function listTools(query?: string, connectionId?: string): Promise<ApiToolInfo[]> {
  const params = new URLSearchParams();
  if (query) params.set("query", query);
  if (connectionId) params.set("connectionId", connectionId);
  const qs = params.toString();
  return json<ApiToolInfo[]>(await fetch(qs ? `${TOOLS_API}?${qs}` : TOOLS_API));
}

export async function enableTool(id: string): Promise<ApiToolInfo> {
  return json<ApiToolInfo>(await fetch(`${TOOLS_API}/${id}/enable`, { method: "POST" }));
}

export async function disableTool(id: string): Promise<ApiToolInfo> {
  return json<ApiToolInfo>(await fetch(`${TOOLS_API}/${id}/disable`, { method: "POST" }));
}

export async function setToolKnowledgeSource(id: string, enabled: boolean): Promise<ApiToolInfo> {
  return json<ApiToolInfo>(
    await fetch(`${TOOLS_API}/${id}/knowledge-source`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ enabled }),
    }),
  );
}

/** Throws with the violation messages joined when the server answers 422. */
export async function invokeTool(
  id: string,
  args: Record<string, unknown>,
): Promise<ToolInvokeResult> {
  const res = await fetch(`${TOOLS_API}/${id}/invoke`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ args }),
  });
  if (res.status === 422) {
    const body = await res.json().catch(() => ({ violations: [] }));
    const messages = (body.violations as ToolViolation[] | undefined)
      ?.map((v) => v.message)
      .join("; ");
    throw new Error(messages || "Arguments violate the tool's schema");
  }
  return json<ToolInvokeResult>(res);
}
